# Generated by Django 3.2 on 2023-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
