# Generated by Django 3.2 on 2023-07-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('wishlist', '0003_alter_wishlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='favourite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='products.product'),
        ),
    ]
