# Generated by Django 3.2 on 2023-07-01 13:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(blank=True, choices=[('extraordinary', 'Extraordinary'), ('perfect', 'Perfect'), ('no-complaints', 'No complaints'), ('can-be-better', 'Can be better'), ('not-recommended', 'Not recommended')], max_length=54, verbose_name='Are you satisfied with our offer and service?')),
                ('age', models.CharField(blank=True, choices=[('18-25', '18-25 years'), ('26-35', '26-35 years'), ('36-45', '36-45 years'), ('46-59', '46-59 years'), ('60', '60 years and +')], max_length=54, verbose_name='How old are you?')),
                ('reason', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('reason_organic', 'They are organic'), ('reason_healthy', 'They are good for your health'), ('reason_fresh', 'They are fresh'), ('reason_taste', 'They taste good'), ('reason_close', 'They are close to home')], max_length=68, verbose_name='Why do you buy our products?')),
                ('comments', models.TextField(blank=True, max_length=254, verbose_name='Do you have any comments?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
