# Generated by Django 3.2 on 2023-07-17 16:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='ratings',
            field=models.CharField(choices=[('extraordinary', 'Extraordinary'), ('perfect', 'Perfect'), ('no-complaints', 'No complaints'), ('can-be-better', 'Can be better'), ('not-recommended', 'Not recommended')], max_length=54, verbose_name='Are you satisfied with our offer and service?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='reason',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('reason_organic', 'They are organic'), ('reason_healthy', 'They are good for your health'), ('reason_fresh', 'They are fresh'), ('reason_taste', 'They taste good'), ('reason_close', 'They are close to home')], max_length=68, verbose_name='Why do you buy our products?'),
        ),
    ]
